### ISSUE TITLE
Remove drawer

### ISSUE THREAD

**Issue by plafue** [plafue/writeily-pro#112]
In my opinion, the drawer does not make much sense at the moment.
The "Notes" button is useless. Importing could be done from a (collapsed) menu in the toolbar, and settings could be accessed through there as well.
What about moving forward towards minimalism and remove it altogether?
Could look something like this:
plafue/writeily-pro@b197420
 (on the current implementation there is a small glitch when activating the search function)

@jffrymrtn what do you think?

**Comment by kud** [comment]
+1 to remove "notes", useless.

**Comment by jffrymrtn** [comment]
Removing Notes is good for me. The original intent for the sidebar was because I was intending to have "Local Notes", "Cloud Notes", then "Settings". But I don't plan on doing integrated cloud sync (GDrive or Dropbox) anytime soon so maybe it can go...

I'm against the collapsed menu though, I'm trying to avoid them. Instead I think "Import" can go to the FAB. Just need a new icon for it...

I'll branch this out into separate tasks for version 1.4

**Comment by plafue** [comment]
Got it! Thanks for your feedback!!

**Comment by kud** [comment]
You're right about priorities, cloud sync isn't necessary for the moment as long as you create "physical" files on the hard disk, not a database you can't export easily.

**Comment by jffrymrtn** [comment]
Actually scratch this task for now.

I've been thinking about it, and sometime in the future, for people who don't use OwnCloud or a very "manual" type of sync (like you guys do), I'll probably implement a separate fragment for Dropbox sync (whose filesystem is totally separate from the local filesystem). This fragment will probably be in the drawer as "Dropbox Notes".

I'm not sure WHEN I'll do sync yet though... But I should know by version 1.5 if I'm doing it at all. If I decide to do it, I'll completely close this issue, but if I decide not to, I'll re-assign this and remove the drawer code.

Backlogging for now :)
